import type { TeamSchemaDocument } from './types';

export const sampleTeamSchema: TeamSchemaDocument = {
  schema_version: '0.1.0',
  team_id: 'software-delivery-team',
  team_name: 'Software Delivery Team',
  departments: [
    {
      department_id: 'product',
      name: 'Product',
      mission: 'Clarify user goals and define acceptance criteria.',
      decision_scope: ['requirements', 'priority', 'acceptance'],
      agents: ['product_owner'],
      handoff_contracts: ['ticket_draft', 'acceptance_criteria'],
    },
    {
      department_id: 'engineering',
      name: 'Engineering',
      mission: 'Design and execute technical implementation plans.',
      decision_scope: ['technical_plan', 'implementation', 'verification'],
      agents: ['tech_lead', 'executor'],
      handoff_contracts: ['implementation_plan', 'pipeline_result'],
    },
  ],
  agents: [
    {
      agent_id: 'product_owner',
      department_id: 'product',
      role: 'Topic Owner',
      model: 'default-reasoning-model',
      metadata: {
        name: 'CEO',
        description: 'Receive user tasks and decompose them into executable ticket chains.',
        profile: 'planning',
        tool_policy: 'delegation_first',
        allowed_commands: ['CHECK_IN', 'NEW_TICKET'],
        required_commands: ['CHECK_IN'],
      },
      description: 'Owns goal clarification, ticket definition and acceptance review.',
      responsibilities: ['clarify_goal', 'define_ticket', 'acceptance_review'],
      input_contract: 'user_request_or_topic',
      output_contract: 'ticket_draft',
      skills: ['requirements_breakdown'],
      mcp_servers: [],
      tools: [],
      memory_access_policy: 'topic_owner_policy',
    },
    {
      agent_id: 'tech_lead',
      department_id: 'engineering',
      role: 'Department Owner',
      model: 'default-reasoning-model',
      metadata: {
        name: 'CTO',
        description: 'Designs the implementation approach and architecture decisions.',
        profile: 'architecture',
        tool_policy: 'read_heavy',
        allowed_commands: ['CHECK_IN', 'NEW_TICKET', 'DELIVERABLE'],
        required_commands: ['CHECK_IN'],
      },
      description: 'Owns technical plan convergence, risk review and stable handoffs.',
      responsibilities: ['technical_plan', 'pipeline_design', 'risk_review'],
      input_contract: 'ticket_draft',
      output_contract: 'implementation_plan',
      skills: ['technical_planning'],
      mcp_servers: ['repository'],
      tools: ['search', 'read_file'],
      memory_access_policy: 'department_owner_policy',
    },
    {
      agent_id: 'executor',
      department_id: 'engineering',
      role: 'Pipeline Step Executor',
      model: 'default-coding-model',
      metadata: {
        name: 'FullStackEngineer',
        description: 'Delivers front-end and back-end implementation artifacts.',
        profile: 'code',
        tool_policy: 'execution_write',
        partials: ['execution'],
        tools: ['get_ticket_summary', 'read_file', 'write_file'],
        allowed_commands: ['CHECK_IN', 'DELIVERABLE'],
        required_commands: ['CHECK_IN', 'DELIVERABLE'],
      },
      description: 'Builds the runnable implementation and reports validation artifacts.',
      responsibilities: ['execute_step', 'produce_handoff', 'report_failure'],
      input_contract: 'pipeline_step_input',
      output_contract: 'pipeline_step_output',
      skills: ['implementation'],
      mcp_servers: ['repository'],
      tools: ['search', 'read_file', 'edit_file', 'run_tests'],
      memory_access_policy: 'ticket_executor_policy',
    },
  ],
  discussion_policy: {
    mode: 'supervisor_led',
    max_rounds: 3,
    supervisor_agent_id: 'product_owner',
    conflict_resolution: 'supervisor_decision',
    required_outputs: ['topic', 'decision', 'ticket_draft'],
  },
  pipeline_policy: {
    one_pipeline_per_ticket: true,
    dag_required: true,
    step_owner_required: true,
    review_before_handoff: true,
  },
  memory_policy: {
    retrieval_mode: 'hybrid_vector_graph',
    vector_store: 'pgvector',
    graph_store: 'local_graph',
    indexed_object_types: ['memory_object', 'topic', 'decision', 'ticket', 'handoff', 'review_result', 'audit_event'],
    retrieval_profiles: [
      {
        profile_id: 'topic_owner_policy',
        allowed_scopes: ['system', 'session', 'topic'],
        max_results: 12,
        max_graph_hops: 2,
        require_reviewed_memory: false,
      },
      {
        profile_id: 'department_owner_policy',
        allowed_scopes: ['system', 'session', 'topic', 'ticket'],
        max_results: 12,
        max_graph_hops: 2,
        require_reviewed_memory: false,
      },
      {
        profile_id: 'ticket_executor_policy',
        allowed_scopes: ['system', 'ticket'],
        max_results: 8,
        max_graph_hops: 1,
        require_reviewed_memory: true,
      },
    ],
    evidence_required_for_outputs: ['decision', 'ticket', 'handoff', 'review_result'],
    conflict_strategy: 'return_conflicts_to_review',
  },
  review_policy: {
    ticket_admission: ['logic_review', 'quality_review'],
    step_completion: ['logic_review', 'quality_review'],
    allowed_results: ['pass', 'revise', 'block'],
  },
};