import { createSlice } from '@reduxjs/toolkit';

import {
  addAgent as addAgentReducer,
  removeAgent as removeAgentReducer,
  updateAgentField as updateAgentFieldReducer,
  updateAgentLlmBinding as updateAgentLlmBindingReducer,
  updateAgentList as updateAgentListReducer,
  updateAgentMetadataField as updateAgentMetadataFieldReducer,
  updateAgentMetadataList as updateAgentMetadataListReducer,
} from '../reducers/agentReducers';
import {
  clearSchemaServiceFeedback as clearSchemaServiceFeedbackReducer,
  schemaLoadFailed as schemaLoadFailedReducer,
  schemaLoadSucceeded as schemaLoadSucceededReducer,
  setDraftSchemaKey as setDraftSchemaKeyReducer,
  setSchemaServiceError as setSchemaServiceErrorReducer,
  setSchemaServiceKeys as setSchemaServiceKeysReducer,
  setSchemaServiceMessage as setSchemaServiceMessageReducer,
  setSchemaServiceStatus as setSchemaServiceStatusReducer,
  startSchemaLoad as startSchemaLoadReducer,
  updateWorkflowLayout as updateWorkflowLayoutReducer,
} from '../reducers/documentReducers';
import {
  clearDiscussionSupervisor as clearDiscussionSupervisorReducer,
  updateDiscussionField as updateDiscussionFieldReducer,
  updateDiscussionNumber as updateDiscussionNumberReducer,
} from '../reducers/discussionReducers';
import {
  addMemoryRetrievalProfile as addMemoryRetrievalProfileReducer,
  removeMemoryPolicy as removeMemoryPolicyReducer,
  removeMemoryRetrievalProfile as removeMemoryRetrievalProfileReducer,
  updateMemoryPolicyField as updateMemoryPolicyFieldReducer,
  updateMemoryPolicyList as updateMemoryPolicyListReducer,
  updateMemoryRetrievalProfileBoolean as updateMemoryRetrievalProfileBooleanReducer,
  updateMemoryRetrievalProfileField as updateMemoryRetrievalProfileFieldReducer,
  updateMemoryRetrievalProfileList as updateMemoryRetrievalProfileListReducer,
  updateMemoryRetrievalProfileNumber as updateMemoryRetrievalProfileNumberReducer,
} from '../reducers/memoryReducers';
import {
  updateDepartmentField as updateDepartmentFieldReducer,
  updateDepartmentList as updateDepartmentListReducer,
} from '../reducers/departmentReducers';
import { selectNode as selectNodeReducer } from '../reducers/selectionReducers';
import {
  addDepartment as addDepartmentReducer,
  removeDepartment as removeDepartmentReducer,
  updateTeamField as updateTeamFieldReducer,
} from '../reducers/teamReducers';
import { initialState } from './editorShared';

const editorSlice = createSlice({
  name: 'editor',
  initialState,
  reducers: {
    selectNode: selectNodeReducer,
    startSchemaLoad: startSchemaLoadReducer,
    schemaLoadSucceeded: schemaLoadSucceededReducer,
    schemaLoadFailed: schemaLoadFailedReducer,
    setSchemaServiceKeys: setSchemaServiceKeysReducer,
    setDraftSchemaKey: setDraftSchemaKeyReducer,
    setSchemaServiceStatus: setSchemaServiceStatusReducer,
    setSchemaServiceError: setSchemaServiceErrorReducer,
    setSchemaServiceMessage: setSchemaServiceMessageReducer,
    clearSchemaServiceFeedback: clearSchemaServiceFeedbackReducer,
    updateWorkflowLayout: updateWorkflowLayoutReducer,
    updateTeamField: updateTeamFieldReducer,
    updateDepartmentField: updateDepartmentFieldReducer,
    updateDepartmentList: updateDepartmentListReducer,
    updateAgentField: updateAgentFieldReducer,
    updateAgentLlmBinding: updateAgentLlmBindingReducer,
    updateAgentList: updateAgentListReducer,
    updateAgentMetadataField: updateAgentMetadataFieldReducer,
    updateAgentMetadataList: updateAgentMetadataListReducer,
    updateDiscussionField: updateDiscussionFieldReducer,
    updateDiscussionNumber: updateDiscussionNumberReducer,
    clearDiscussionSupervisor: clearDiscussionSupervisorReducer,
    removeMemoryPolicy: removeMemoryPolicyReducer,
    updateMemoryPolicyField: updateMemoryPolicyFieldReducer,
    updateMemoryPolicyList: updateMemoryPolicyListReducer,
    addMemoryRetrievalProfile: addMemoryRetrievalProfileReducer,
    removeMemoryRetrievalProfile: removeMemoryRetrievalProfileReducer,
    updateMemoryRetrievalProfileField: updateMemoryRetrievalProfileFieldReducer,
    updateMemoryRetrievalProfileList: updateMemoryRetrievalProfileListReducer,
    updateMemoryRetrievalProfileNumber: updateMemoryRetrievalProfileNumberReducer,
    updateMemoryRetrievalProfileBoolean: updateMemoryRetrievalProfileBooleanReducer,
    addDepartment: addDepartmentReducer,
    removeDepartment: removeDepartmentReducer,
    addAgent: addAgentReducer,
    removeAgent: removeAgentReducer,
  },
});

export const {
  clearSchemaServiceFeedback,
  addAgent,
  addDepartment,
  removeAgent,
  removeDepartment,
  schemaLoadFailed,
  schemaLoadSucceeded,
  selectNode,
  setDraftSchemaKey,
  setSchemaServiceError,
  setSchemaServiceKeys,
  setSchemaServiceMessage,
  setSchemaServiceStatus,
  startSchemaLoad,
  updateWorkflowLayout,
  updateAgentField,
  updateAgentLlmBinding,
  updateAgentList,
  updateAgentMetadataField,
  updateAgentMetadataList,
  clearDiscussionSupervisor,
  updateDepartmentField,
  updateDepartmentList,
  updateDiscussionField,
  updateDiscussionNumber,
  addMemoryRetrievalProfile,
  removeMemoryPolicy,
  removeMemoryRetrievalProfile,
  updateMemoryPolicyField,
  updateMemoryPolicyList,
  updateMemoryRetrievalProfileBoolean,
  updateMemoryRetrievalProfileField,
  updateMemoryRetrievalProfileList,
  updateMemoryRetrievalProfileNumber,
  updateTeamField,
} = editorSlice.actions;

export const editorReducer = editorSlice.reducer;